---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-1
    image: docker.io/pycontribs/centos:7
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: ansible
